apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: test
  namespace: frr-k8s-system
spec:
  bgp:
    routers:
    - asn: 64515
      neighbors:
      - address: 192.169.10.0
        asn: 64514
        toReceive:
          allowed:
            mode: all
        toAdvertise:
          allowed:
            mode: all
      prefixes:
        - 10.244.1.3/32
