apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
    app.kubernetes.io/name: controller
    app.kubernetes.io/instance: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: controller
        app: controller
    spec:
      containers:
      - command:
        - /controller
        args:
        - "--nodename=$(NODE_NAME)"
        - "--loglevel=debug"
        - "--namespace=$(NAMESPACE)"
        - "--frrconfig=/etc/frr/frr.conf"
        image: router:latest
        imagePullPolicy: IfNotPresent
        name: controller
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN", "NET_BIND_SERVICE"]
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /run/containerd/containerd.sock
          name: varrun
          subPath: containerd.sock
        - mountPath: /run/netns
          name: runns
          mountPropagation: HostToContainer
        - mountPath: /etc/frr/
          name: frr-config
          mountPropagation: HostToContainer
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      volumes:
      - name: runns
        hostPath:
          path: /run/netns
      - name: varrun
        hostPath:
          path: /run/containerd
      - name: frr-config
        hostPath:
          path: /etc/perouter/frr
          type: DirectoryOrCreate
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      serviceAccountName: controller
      hostNetwork: true
      hostPID: true
