apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: openperouter
    app.kubernetes.io/managed-by: kustomize
  name: perouter-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: perouter-role
subjects:
- kind: ServiceAccount
  name: perouter
  namespace: system

