apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: openperouter
    app.kubernetes.io/managed-by: kustomize
  name: perouter-role
  namespace: system
rules:
  # Without a minimal set of rules, the operator-sdk will not generate the perouter ServiceAccount, 
  # leading to a deployment failure of the perouter DaemonSet
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get

