# This file is present in openshift-kni fork only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-scc-role
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: openperouter
    app.kubernetes.io/managed-by: kustomize
  name: perouter-privileged-scc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-scc-role
subjects:
- kind: ServiceAccount
  name: perouter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: openperouter
    app.kubernetes.io/managed-by: kustomize
  name: controller-privileged-scc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-scc-role
subjects:
- kind: ServiceAccount
  name: controller
