apiVersion: openpe.openperouter.github.io/v1alpha1
kind: Underlay
metadata:
  name: underlay
  namespace: openperouter-system
spec:
  asn: 64514
  vtepcidr:  100.65.0.0/24
  nics:
    - cleth1
  neighbors:
    - asn: 64512
      address: 192.168.11.2
