---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: l3vnis.openpe.openperouter.github.io
spec:
  group: openpe.openperouter.github.io
  names:
    kind: L3VNI
    listKind: L3VNIList
    plural: l3vnis
    singular: l3vni
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          L3VNI represents a VXLan L3VNI to receive EVPN type 5 routes
          from.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: L3VNISpec defines the desired state of VNI.
            properties:
              hostsession:
                description: HostSession is the configuration for the host session.
                properties:
                  asn:
                    description: |-
                      ASN is the local AS number to use to establish a BGP session with
                      the default namespace.
                    format: int32
                    maximum: 4294967295
                    minimum: 1
                    type: integer
                  hostasn:
                    description: |-
                      ASN is the expected AS number for a BGP speaking component running in
                      the default network namespace. If not set, the ASN field is going to be used.
                    format: int32
                    maximum: 4294967295
                    minimum: 0
                    type: integer
                  localcidr:
                    description: |-
                      LocalCIDR is the CIDR configuration for the veth pair
                      to connect with the default namespace. The interface under
                      the PERouter side is going to use the first IP of the cidr on all the nodes.
                      At least one of IPv4 or IPv6 must be provided.
                    properties:
                      ipv4:
                        description: |-
                          IPv4 is the IPv4 CIDR to be used for the veth pair
                          to connect with the default namespace. The interface under
                          the PERouter side is going to use the first IP of the cidr on all the nodes.
                        type: string
                      ipv6:
                        description: |-
                          IPv6 is the IPv6 CIDR to be used for the veth pair
                          to connect with the default namespace. The interface under
                          the PERouter side is going to use the first IP of the cidr on all the nodes.
                        type: string
                    type: object
                    x-kubernetes-validations:
                    - message: LocalCIDR can't be changed
                      rule: self == oldSelf
                required:
                - asn
                - hostasn
                - localcidr
                type: object
              vni:
                description: VNI is the VXLan VNI to be used
                format: int32
                maximum: 4294967295
                minimum: 0
                type: integer
              vrf:
                description: VRF is the name of the linux VRF to be used inside the
                  PERouter namespace.
                maxLength: 15
                pattern: ^[a-zA-Z][a-zA-Z0-9_-]*$
                type: string
              vxlanport:
                default: 4789
                description: VXLanPort is the port to be used for VXLan encapsulation.
                format: int32
                type: integer
            required:
            - vrf
            type: object
            x-kubernetes-validations:
            - message: hostASN must be different from asn
              rule: '!has(self.hostsession) || self.hostsession.hostasn != self.hostsession.asn'
          status:
            description: L3VNIStatus defines the observed state of L3VNI.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
